# LOCAL ONLY: public registration + explicit first-admin bootstrap, then real Catalog HTTP commands.
# No product-table SQL writes, file scanning, model calls, or silent overrides of existing products.
[CmdletBinding()]
param([switch]$BootstrapAdmin)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'local-common.ps1')
$settings = Get-DayuSettings
$repo = $DayuRepo
$base = $settings.BaseUrl
$config = @{}
foreach ($line in [IO.File]::ReadAllLines((Join-Path $repo '.env.local-admin'))) {
    if ($line -match '^([A-Z_]+)=(.*)$') { $config[$matches[1]] = $matches[2].Trim() }
}
$email = $config['DAYU_LOCAL_ADMIN_EMAIL']
$password = $config['DAYU_LOCAL_ADMIN_PASSWORD']
if ($email -ne 'local-admin@dayu.test' -or [string]::IsNullOrWhiteSpace($password)) {
    throw 'Expected the dedicated local administrator credentials.'
}
$session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$script:csrf = $null
function Invoke-LocalApi([string]$Method, [string]$Path, $Payload = $null) {
    $arguments = @{Uri=($base+$Path); Method=$Method; WebSession=$session; TimeoutSec=20; ErrorAction='Stop'}
    if ($script:csrf) { $arguments.Headers = @{'X-CSRF-TOKEN'=$script:csrf} }
    if ($null -ne $Payload) {
        $arguments.ContentType = 'application/json; charset=utf-8'
        $arguments.Body = [Text.Encoding]::UTF8.GetBytes(($Payload | ConvertTo-Json -Depth 8 -Compress))
    }
    try { Invoke-RestMethod @arguments }
    catch {
        $status = if ($_.Exception.Response) { [int]$_.Exception.Response.StatusCode } else { 'NETWORK' }
        throw "Local API failed: $Method $Path; status=$status. Credentials/request bodies are not logged."
    }
}
function Invoke-LocalSql([string]$Sql) {
    $result = $Sql | & docker exec -i $settings.Container sh -c 'MYSQL_PWD=$MARIADB_PASSWORD exec mariadb --user=dayu dayu --batch --skip-column-names'
    if ($LASTEXITCODE -ne 0) { throw 'Local bootstrap database command failed.' }
    return $result
}

# Never promote an existing account or bypass an existing administrator. Bootstrap only a fresh database.
if ($BootstrapAdmin) {
    $count = [int](Invoke-LocalSql 'SELECT COUNT(*) FROM users;')
    if ($count -ne 0) { throw 'Bootstrap requires an empty users table. Log in to the existing admin instead.' }
}
$anonymous = Invoke-LocalApi GET '/api/v1/session'
$script:csrf = $anonymous.csrfToken
if ($BootstrapAdmin) {
    $registered = Invoke-LocalApi POST '/api/v1/users' @{email=$email;password=$password;organization='Dayu local development'}
    $script:csrf = $registered.csrfToken
    $changed = Invoke-LocalSql "UPDATE users SET role='ADMIN' WHERE email='local-admin@dayu.test' AND role='USER' AND status='ACTIVE'; SELECT ROW_COUNT();"
    if ([int]$changed -ne 1) { throw 'First administrator bootstrap did not change exactly one local account.' }
}
$authenticated = Invoke-LocalApi POST '/api/v1/session' @{email=$email;password=$password}
$script:csrf = $authenticated.csrfToken
$password = $null
$config.Clear()

$manifest = Get-Content -LiteralPath (Join-Path $repo 'infra/local-products.json') -Raw -Encoding UTF8 | ConvertFrom-Json
foreach ($product in $manifest) {
    $existing = Invoke-LocalApi GET ("/api/v1/admin/products?code="+$product.code)
    if ($null -ne $existing -and $existing.Count -gt 0) {
        Write-Output "SKIPPED existing product: $($product.code); no metadata or modes overwritten."
        continue
    }
    $isCloud = $product.family -eq 'CPP'
    $isPrecipitation = $product.family -eq 'REPPIC_PRECIP'
    $source = if ($isCloud) { 'Cloud products generated by the research group from FY-4B/AGRI observations; not official FY-4B L2 products.' }
        elseif ($isPrecipitation) { 'Research-group RePPIC-Net products; one NC may contain both precipitation phase and rate.' }
        else { 'FY-4B/AGRI upstream processed products. This platform does not process or distribute raw HDF.' }
    $body = @{code=$product.code;family=$product.family;nameZh=$product.nameZh;nameEn=$product.nameEn;
        unit=$product.unit;sortOrder=$product.sortOrder;colorbarRequired=$product.colorbarRequired;colorbarPath=$null;
        descriptionZh=($product.nameZh+'。本地目录初始化；数据是否可用由后续文件索引决定。');
        descriptionEn=($product.nameEn+'. Local catalog initialization; availability depends on indexed files.');
        producer=$(if ($isCloud -or $isPrecipitation) {'Research group'} else {'FY-4B/AGRI upstream processing'});
        algorithmName=$(if ($isPrecipitation) {'RePPIC-Net'} else {$null});sourceDescription=$source;officialSourceUrl=$null}
    $created = Invoke-LocalApi POST '/api/v1/admin/products' $body
    $id = $created.productId
    Invoke-LocalApi PUT "/api/v1/admin/products/$id/modes/REALTIME" @{enabled=$true;staleAfterMinutes=$product.realtimeMinutes} | Out-Null
    if ($null -ne $product.forecastMinutes) {
        Invoke-LocalApi PUT "/api/v1/admin/products/$id/modes/FORECAST" @{enabled=$true;staleAfterMinutes=$product.forecastMinutes} | Out-Null
    }
    if ($product.colorbarRequired) {
        Write-Output "DRAFT: $($product.code); modes configured; required colorbar not available."
    } else {
        $published = Invoke-LocalApi POST "/api/v1/admin/products/$id/publish"
        if ($published.status -ne 'PUBLISHED') { throw 'Unexpected publication response.' }
        Write-Output "PUBLISHED: $($product.code)"
    }
}
Invoke-LocalApi DELETE '/api/v1/session' | Out-Null
Write-Output 'Local product initialization finished. No assets were scanned.'
